### ISSUE TITLE
improvement: switch to java.time.*, and core library desugaring

### ISSUE THREAD

**Issue by SerggioC** [kodecocodes/adva-materials#33]
Switch to java.time.*, and core library desugaring instead of ThreeTen Android Backport.

**Comment by rcosteira79** [comment]
Hi there! First of all, so sorry for the ridiculously late reply. I thought I had notifications on this, but apparently I didn't 🤦

Anyway, thanks for your input! We followed your advice and are now using library desugaring for the second edition of the book :)
